export const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `Parting the glossy leaves I discovered a buff-tailed bumblebee ensnared in an orb web.`,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `Phytoplankton serve as the base of the aquatic food web, providing an essential ecological function for all aquatic life. `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `A common metric used to quantify food web trophic structure is food chain length..`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Our next foray into the menu was a wild mushroom cream soup with Toscanini truffle oil and garlic flakes. `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `A proper menu is forthcoming, but there's always a small selection of chow to be had. `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Experts fear a humanitarian catastrophe if food isn't delivered to the refugees soon.`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `The restaurant's food is excellent, but beware the chili if you don't like spicy food. `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `They came on a mission of mercy to provide food and medical care for starving children.`,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `Manufacturing, printing, publishing and food processing also play major roles in the city's economy.`,
  },
];
